[tool.poetry]
name = "dydx"
version = "0.0.1"
description = ""
packages = [
    { include = "dydx" },
]
authors = ["0xMagus <rico@nemo.ventures>"]

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^0.21.0"
loguru = "^0.6.0"
web3 = "^5.31.1"
dydx-v3-python = { git = "git@github.com:dydxprotocol/dydx-v3-python.git", rev = "dc7705e" }
aiohttp = "^3.8.3"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
black = "^22.10"
mypy = "^0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py39']
line-length = 120
exclude = '''
/(
    \.git
  | \.pytest_cache
  | \.venv
  | __pycache
)/
'''
